### ISSUE TITLE
timeline KeyError: 'verb'

### ISSUE THREAD

**Issue by bufke** [thoas/django-sequere#8]
I create a timeline like:

```
class CommentAction(Action):                                                     
    verb = "comment"                                                             

class ProfileSequere(ModelBase):                                                 
     identifier = "profile"                                                       
    actions = (CommentAction,)                                                   

register(Profile, ProfileSequere) 
```

```
timeline = Timeline(profile)                                                 
timeline.save(CommentAction(actor=profile))
print(timeline.get_private())
```

On the get_private line it fails. get_private_count() actually works and returns the count.

`pipe.execute()` returns `[]`

Stacktrace

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 236, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.4/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/site-packages/six.py", line 659, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/contrib/comments/views/comments.py", line 127, in post_comment
    request=request
  File "/usr/local/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/code/core/views.py", line 39, in comment_activity
    print(timeline.get_private())
  File "/usr/local/lib/python3.4/site-packages/sequere/query.py", line 51, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/usr/local/lib/python3.4/site-packages/sequere/query.py", line 38, in __getitem__
    return k.step and list(self.transform(self.qs))[::k.step] or self.transform(self.qs)
  File "/usr/local/lib/python3.4/site-packages/sequere/contrib/timeline/query.py", line 38, in transform
    return self._transform(scores)
  File "/usr/local/lib/python3.4/site-packages/sequere/contrib/timeline/query.py", line 51, in _transform
    for data in pipe.execute()]
  File "/usr/local/lib/python3.4/site-packages/sequere/contrib/timeline/query.py", line 51, in <listcomp>
    for data in pipe.execute()]
  File "/usr/local/lib/python3.4/site-packages/sequere/contrib/timeline/action.py", line 86, in from_data
    verb = data['verb']
KeyError: 'verb'
```

**Comment by bufke** [comment]
Settings 

```
BROKER_URL = 'redis://redis:6379/0'
SEQUERE_BACKEND_CLASS = 'sequere.backends.redis.RedisBackend'
SEQUERE_REDIS_CONNECTION = SEQUERE_TIMELINE_REDIS_CONNECTION = BROKER_URL
```

**Comment by thoas** [comment]
fixed in master, will publish it on pypi when travis will be green.

**Comment by bufke** [comment]
Still having issues with 0.2.3 from pypi. Probably a similar issue. I removed all data from my redis instance to rule out the possibility of old data. I get 

```
worker_1 | Traceback (most recent call last):
worker_1 |   File "/usr/local/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
worker_1 |     R = retval = fun(*args, **kwargs)
worker_1 |   File "/usr/local/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
worker_1 |     return self.run(*args, **kwargs)
worker_1 |   File "/usr/local/lib/python3.4/site-packages/sequere/contrib/timeline/tasks.py", line 68, in import_actions
worker_1 |     logger=import_actions.get_logger())
worker_1 |   File "/usr/local/lib/python3.4/site-packages/sequere/contrib/timeline/tasks.py", line 44, in populate_actions
worker_1 |     from_instance = manager.get_from_uid(from_uid)
worker_1 |   File "/usr/local/lib/python3.4/site-packages/sequere/backends/redis/managers.py", line 87, in get_from_uid
worker_1 |     klass = registry.identifiers.get(data['identifier'])
worker_1 | KeyError: 'identifier'
```

Redis looks like
![screenshot from 2015-03-26 11 06 11](https://cloud.githubusercontent.com/assets/739307/6849216/343e1390-d3a8-11e4-86fd-d8b31d3ce62c.png)

**Comment by thoas** [comment]
Hmm... You are using redis with an url, I have forgotten the `decode_responses` in this [case](https://github.com/thoas/django-sequere/blob/master/sequere/utils.py#L100)

**Comment by thoas** [comment]
Fixed in master, let me know before publishing on pypi.
